### ISSUE TITLE
Update Theme for CNCF Sandbox Onboarding

### ISSUE THREAD

**Issue by tobru** [k8up-io/antora-ui-default#3]
As part of the onboarding process the Website needs to be slightly adapted, mainly the footer.

See part "Website: ensure LF footer is there and website guidelines followed" of the following issue:

- https://github.com/cncf/toc/issues/753

More details are documented here: https://github.com/cncf/foundation/blob/master/website-guidelines.md

**Comment by akosma** [comment]
Documentation website updated with new footer and without VSHN menu.
