### ISSUE TITLE
Add Trademark disclaimer to Antora site

### ISSUE THREAD

**Issue by tobru** [k8up-io/antora-ui-default#6]
According to https://clomonitor.io/projects/cncf/k8up#k8up_legal we need to add a trademark disclaimer to the website: https://clomonitor.io/docs/topics/checks/#trademark-disclaimer

Looking at some other examples, it could be that text:

> The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our [Trademark Usage page](https://www.linuxfoundation.org/trademark-usage).

**Comment by akosma** [comment]
Solved, deploying
